### PR TITLE
feat(hedera): added support for hedera network by krypc team

### PR DESCRIPTION
**Pull request by piruthivi3232**

### CODE REVIEW

**Comment by superical** [comment]
Please update branch and fix all issues.

**Comment by piruthivi3232** [comment]
issue resolved. guide me if i am doing wrong

**Comment by superical** [comment]
Your changes have conflicts.

**Comment by piruthivi3232** [comment]
conflicts resolved.

**Comment by piruthivi3232** [comment]
check again

**Comment by superical** [comment]
Pls fix conflicts.

**Comment by piruthivi3232** [comment]
conflicts resolved.

**Review by superical — APPROVED** [review]

**Pull request merged**
